// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSampleReact.Data.Migrater;

namespace WebApiSampleReact.Data.Migrater.CarDealershipMigrations
{
    [DbContext(typeof(CarDealershipContext))]
    partial class CarDealershipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApiSampleReact.Data.Migrater.CarEntity", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Color")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("HasHeatedSeats")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLowMiles")
                        .HasColumnType("bit");

                    b.Property<bool>("HasNavigation")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPowerWindows")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSunroof")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFourWheelDrive")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasMaxLength(150)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("_id");

                    b.HasIndex("_id")
                        .HasAnnotation("SqlServer:Include", new[] { "Year", "Price", "Make", "IsFourWheelDrive", "HasSunroof", "HasPowerWindows", "HasNavigation", "HasLowMiles", "HasHeatedSeats", "Color" });

                    b.ToTable("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
